#!/usr/bin/env python3
"""Build .specify/ontology/snapshots/entity-coverage.snapshot.json for AES Logistics.

Records hashes of the coverage sources + computed coverage summary (required vs
deferred vs exceptions) so validate_spec.py can detect drift and missing classes.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
from ontology_entity_coverage import (  # noqa: E402
    REQUIRED_CLASSES,
    DEFERRED,
    COVERAGE_EXCEPTIONS,
    parse_data_model_entities,
    coverage_freshness_files,
)

ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
SNAPSHOT = ONTOLOGY / "snapshots" / "entity-coverage.snapshot.json"


def main() -> int:
    file_hashes = {}
    for p in coverage_freshness_files(ROOT):
        if not p.is_file():
            raise SystemExit(f"error: coverage source missing: {p.relative_to(ROOT)}")
        rel = str(p.relative_to(ROOT)).replace("\\", "/")
        file_hashes[rel] = hashlib.sha256(p.read_bytes()).hexdigest()

    dm = require_get_data_model()
    required, deferred = parse_data_model_entities(dm)
    snap = {
        "$schemaComment": "AUTO-GENERATED by .specify/scripts/extract_entity_coverage.py — DO NOT HAND-EDIT.",
        "fileHashes": file_hashes,
        "required": required,
        "deferred": deferred,
        "exceptions": COVERAGE_EXCEPTIONS,
        "counts": {
            "required": len(required),
            "deferred": len(deferred),
            "exceptions": len(COVERAGE_EXCEPTIONS),
        },
    }
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(json.dumps(snap, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {SNAPSHOT.relative_to(ROOT)}")
    return 0


def require_get_data_model() -> str:
    dm = ROOT / "specs" / "001-server" / "data-model.md"
    if not dm.is_file():
        raise SystemExit("error: missing specs/001-server/data-model.md")
    return dm.read_text(encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())