#!/usr/bin/env python3
"""Build .specify/ontology/snapshots/schema.snapshot.json for AES Logistics.

JSON-driven domain: hashes the two authoritative schema sources (data-model.md
and the server code constants) and records the store->class map + per-class
field lists so generate_ontology.py can emit the structural TBox deterministically.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
from ontology_map import STORE_TO_CLASS, ENTITY_TO_CLASS, CLASS_ORDER  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
SNAPSHOT = ONTOLOGY / "snapshots" / "schema.snapshot.json"

# Authoritative sources that define the data model (hash -> freshness).
SOURCE_FILES = [
    "specs/001-server/data-model.md",
    "server/scheduling.py",
    "server/inventory.py",
]

# Per-class emitted fields (curated; mirrors the data-model.md record shapes).
# Key = class name; value = list of {name, range(xsd), object(object-true)}
CLASS_FIELDS: dict[str, list[dict]] = {
    "Delivery": [
        {"name": "entityId", "range": "string"},
        {"name": "jobNumber", "range": "string"},
        {"name": "deliveryDate", "range": "string"},
        {"name": "receiverName", "range": "string"},
        {"name": "receiverEmail", "range": "string"},
        {"name": "receiverPhone", "range": "string"},
        {"name": "pmEmail", "range": "string"},
        {"name": "siteAddress", "range": "string"},
        {"name": "customerName", "range": "string"},
        {"name": "customerPo", "range": "string"},
        {"name": "jobName", "range": "string"},
        {"name": "deliveryMethod", "range": "string"},
        {"name": "calendarEventUid", "range": "string", "object": True},
        {"name": "assignedDriver", "range": "string"},
        {"name": "status", "range": "string"},
        {"name": "ticketSource", "range": "string"},
        {"name": "reminderSent", "range": "boolean"},
        {"name": "createdAt", "range": "dateTime"},
        {"name": "packedConfirmed", "range": "boolean"},
    ],
    "InventoryEntry": [
        {"name": "entityId", "range": "string"},
        {"name": "jobNumber", "range": "string"},
        {"name": "poNumber", "range": "string"},
        {"name": "pmEmail", "range": "string"},
        {"name": "confirmedBy", "range": "string"},
        {"name": "confirmedAt", "range": "dateTime"},
        {"name": "palletCount", "range": "integer"},
        {"name": "removed", "range": "boolean"},
        {"name": "removedReason", "range": "string"},
        {"name": "comment", "range": "string"},
    ],
    "JobDirectoryEntry": [
        {"name": "jobNumber", "range": "string"},
        {"name": "pmEmail", "range": "string"},
    ],
    "CalendarEvent": [
        {"name": "uid", "range": "string"},
        {"name": "title", "range": "string"},
        {"name": "startIso", "range": "dateTime"},
    ],
    "DeliveryTicket": [
        {"name": "filename", "range": "string"},
        {"name": "ticketSource", "range": "string"},
    ],
    "LineItem": [
        {"name": "description", "range": "string"},
        {"name": "quantity", "range": "integer"},
        {"name": "type", "range": "string"},
        {"name": "boxes", "range": "integer"},
        {"name": "modelNumber", "range": "string"},
        {"name": "mfg", "range": "string"},
    ],
    "LocationSlit": [
        {"name": "location", "range": "string"},
        {"name": "count", "range": "integer"},
    ],
    "Geotag": [
        {"name": "latitude", "range": "decimal"},
        {"name": "longitude", "range": "decimal"},
    ],
    "SupplyItem": [
        {"name": "name", "range": "string"},
        {"name": "onHandQuantity", "range": "integer"},
        {"name": "minThreshold", "range": "integer"},
        {"name": "supplyStatus", "range": "string"},
    ],
    "JitNeed": [
        {"name": "jobNumber", "range": "string"},
        {"name": "neededByDate", "range": "date"},
        {"name": "neededQuantity", "range": "integer"},
    ],
    "Geofence": [
        {"name": "centerLatitude", "range": "decimal"},
        {"name": "centerLongitude", "range": "decimal"},
        {"name": "radiusMeters", "range": "integer"},
        {"name": "geofenceTrigger", "range": "string"},
    ],
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_snapshot() -> dict:
    file_hashes = {}
    missing = []
    for rel in SOURCE_FILES:
        p = ROOT / rel
        if not p.is_file():
            missing.append(rel)
            continue
        file_hashes[rel] = _sha256(p)
    concatenated = b"".join(
        (ROOT / rel).read_bytes() for rel in SOURCE_FILES if (ROOT / rel).is_file()
    )
    return {
        "$schemaComment": "AUTO-GENERATED by .specify/scripts/extract_schema_snapshot.py — DO NOT HAND-EDIT.",
        "fileHashes": file_hashes,
        "sourcesSha256": hashlib.sha256(concatenated).hexdigest(),
        "storeToClass": {k: v for k, v in STORE_TO_CLASS.items()},
        "entityToClass": ENTITY_TO_CLASS,
        "classOrder": CLASS_ORDER,
        "classes": {c: CLASS_FIELDS.get(c, []) for c in CLASS_ORDER},
        "missingSources": missing,
    }


def main() -> int:
    snap = build_snapshot()
    if snap["missingSources"]:
        print(
            "warning: schema snapshot references missing sources: "
            + ", ".join(snap["missingSources"]),
            file=sys.stderr,
        )
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(json.dumps(snap, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {SNAPSHOT.relative_to(ROOT)} ({len(snap['classes'])} classes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())