#!/usr/bin/env python3
"""Build .specify/ontology/snapshots/status-vocab.snapshot.json for AES Logistics.

Assert the intentional closed vocabularies actually appear in the live sources
(hash + literal-set / substring check), then write the snapshot. If a location
is renamed or a status added, this fails instead of silently drifting.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
from ontology_vocabularies import iter_vocabularies  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
SNAPSHOT = ONTOLOGY / "snapshots" / "status-vocab.snapshot.json"

# Provenance file -> assert matching literal present (cheap drift guard).
PROVENANCE_ASSERT: dict[str, str] = {
    "server/scheduling.py": "scheduled",
    "server/inventory.py": "Warehouse",
    "specs/001-server/data-model.md": "packed_for_outgoing_delivery",
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    file_hashes = {}
    errors = []
    for rel, literal in PROVENANCE_ASSERT.items():
        p = ROOT / rel
        if not p.is_file():
            errors.append(f"missing provenance source: {rel}")
            continue
        file_hashes[rel] = _sha256(p)
        if literal not in p.read_text(encoding="utf-8"):
            errors.append(f"closed-vocab provenance literal missing from {rel}: {literal!r}")

    vocabs: dict[str, dict] = {}
    for target_class, e in iter_vocabularies():
        vocabs[e["id"]] = {
            "id": e["id"],
            "property": e["property"],
            "targetClass": target_class,
            "required": e["required"],
            "values": e["values"],
            "provenance": e["provenance"],
            "kind": "intentional_closed_set",
            "note": e["note"],
        }

    if errors:
        for err in errors:
            print(f"error: {err}", file=sys.stderr)
        return 1

    concatenated = b"".join(
        (ROOT / rel).read_bytes() for rel in PROVENANCE_ASSERT if (ROOT / rel).is_file()
    )
    snap = {
        "$schemaComment": "AUTO-GENERATED by .specify/scripts/extract_status_vocabularies.py — DO NOT HAND-EDIT.",
        "fileHashes": file_hashes,
        "sourcesSha256": hashlib.sha256(concatenated).hexdigest(),
        "vocabularies": vocabs,
    }
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(json.dumps(snap, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {SNAPSHOT.relative_to(ROOT)} ({len(vocabs)} vocabularies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())