#!/usr/bin/env python3
"""Regenerate aesl_domain.generated.ttl + aesl_domain.shacl.enums.ttl.

JSON-driven domain: reads the schema + status-vocab snapshots and emits the
structural TBox (class stubs + datatype/object props) plus blocking sh:in lists.
Do not hand-edit the outputs. Run after extract_schema_snapshot.py and
extract_status_vocabularies.py (or just this script, which refreshes both).

    python3 .specify/scripts/generate_ontology.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY = ROOT / ".specify" / "ontology"
OUT = ONTOLOGY / "aesl_domain.generated.ttl"
OUT_SHACL_ENUMS = ONTOLOGY / "aesl_domain.shacl.enums.ttl"
SNAPSHOT = ONTOLOGY / "snapshots" / "schema.snapshot.json"
VOCAB_SNAPSHOT = ONTOLOGY / "snapshots" / "status-vocab.snapshot.json"
EXTRACT = SCRIPTS / "extract_schema_snapshot.py"
EXTRACT_VOCAB = SCRIPTS / "extract_status_vocabularies.py"

NS = "http://aes-lighting.internal/logistics#"

HEADER = """# AUTO-GENERATED by .specify/scripts/generate_ontology.py — DO NOT EDIT.
# Source: .specify/ontology/snapshots/schema.snapshot.json (+ status-vocab).
@prefix aesl: <http://aes-lighting.internal/logistics#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix dct:  <http://purl.org/dc/terms/> .

<http://aes-lighting.internal/logistics/generated>
    a owl:Ontology ;
    dct:title "AES Logistics Generated Structural TBox" ;
    dct:description "Structural classes and properties extracted from the JSON data model." ;
    owl:versionInfo "0.1.0" ;
    rdfs:comment "Regenerate with extract_schema_snapshot.py then generate_ontology.py" .
"""


def _xsd(range_: str) -> str:
    return {
        "integer": "xsd:integer",
        "boolean": "xsd:boolean",
        "dateTime": "xsd:dateTime",
        "decimal": "xsd:decimal",
        "double": "xsd:double",
    }.get(range_, "xsd:string")


def refresh(name: str, script: Path, snapshot: Path) -> dict:
    proc = subprocess.run(
        [sys.executable, str(script)], cwd=str(ROOT), capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise RuntimeError(f"{name} failed:\n{proc.stdout}\n{proc.stderr}")
    if proc.stdout.strip():
        print(proc.stdout.strip())
    return json.loads(snapshot.read_text(encoding="utf-8"))


def build_generated(snap: dict) -> str:
    lines: list[str] = [HEADER.rstrip(), ""]
    for cls in snap.get("classOrder", []):
        lines.append(f"aesl:{cls}")
        lines.append("    a owl:Class ;")
        lines.append(f'    rdfs:label "{cls}" ;')
        lines.append(
            f'    rdfs:comment "Generated class stub for {cls}; curated axioms refine hierarchy." .'
        )
        lines.append("")
        for f in snap.get("classes", {}).get(cls, []):
            if f.get("object"):
                lines.append(f"aesl:has{f['name']}")
                lines.append("    a owl:ObjectProperty ;")
                lines.append(f'    rdfs:label "{cls}.{f["name"]}" ;')
                lines.append(f"    rdfs:domain aesl:{cls} ;")
                lines.append(f"    rdfs:range aesl:{f['name']} ;")
            else:
                lines.append(f"aesl:{f['name']}")
                lines.append("    a owl:DatatypeProperty ;")
                lines.append(f'    rdfs:label "{cls}.{f["name"]}" ;')
                lines.append(f"    rdfs:domain aesl:{cls} ;")
                lines.append(f"    rdfs:range {_xsd(f.get('range', 'string'))} ;")
            lines.append(
                f'    rdfs:comment "Generated structural property for {cls}.{f["name"]}." .'
            )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_shacl_enums(vocab: dict) -> str:
    vocabs = vocab.get("vocabularies") or {}
    lines: list[str] = [
        "# AUTO-GENERATED by .specify/scripts/generate_ontology.py — DO NOT EDIT.",
        "# Blocking SHACL enum constraints from status-vocab.snapshot.json",
        "# (intentional_closed_set via extract_status_vocabularies.py).",
        "# Loaded with aesl_domain.shacl.ttl by validate_instances.py.",
        "# Do not hand-duplicate sh:in values in curated SHACL.",
        "@prefix aesl: <http://aes-lighting.internal/logistics#> .",
        "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
        "@prefix sh:   <http://www.w3.org/ns/shacl#> .",
        "@prefix dct:  <http://purl.org/dc/terms/> .",
        "",
        "<http://aes-lighting.internal/logistics/shacl-enums>",
        "    a owl:Ontology ;",
        '    dct:title "AES Logistics SHACL Enum Shapes (generated)" ;',
        '    owl:versionInfo "0.1.0" ;',
        '    rdfs:comment "Generator-owned sh:in lists. Regenerate with generate_ontology.py." .',
        "",
    ]
    by_class: dict[str, list[dict]] = {}
    for e in vocabs.values():
        by_class.setdefault(e["targetClass"], []).append(e)
    for class_name in sorted(by_class):
        entries = sorted(by_class[class_name], key=lambda e: e["property"])
        lines.append("#" * 65)
        lines.append(f"# {class_name} closed vocabularies")
        lines.append("#" * 65)
        lines.append("")
        lines.append(f"aesl:{class_name}EnumShape")
        lines.append("    a sh:NodeShape ;")
        lines.append(f"    sh:targetClass aesl:{class_name} ;")
        n = len(entries)
        for i, e in enumerate(entries):
            vals = " ".join(f'"{v}"' for v in e["values"])
            term = "." if i == n - 1 else " ;"
            lines.append("    sh:property [")
            lines.append(f"        sh:path aesl:{e['property']} ;")
            if e["required"]:
                lines.append("        sh:minCount 1 ;")
            lines.append("        sh:maxCount 1 ;")
            lines.append("        sh:datatype xsd:string ;")
            lines.append(f"        sh:in ( {vals} ) ;")
            lines.append(
                f'        sh:message "{e["property"]} must be a closed {e["id"]} value from live sources" ;'
            )
            lines.append(f"    ]{term}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    try:
        snap = refresh("extract_schema_snapshot.py", EXTRACT, SNAPSHOT)
        vocab = refresh("extract_status_vocabularies.py", EXTRACT_VOCAB, VOCAB_SNAPSHOT)
    except Exception as exc:  # noqa: BLE001
        print(f"error: {exc}", file=sys.stderr)
        return 1
    OUT.write_text(build_generated(snap), encoding="utf-8")
    OUT_SHACL_ENUMS.write_text(build_shacl_enums(vocab), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"Wrote {OUT_SHACL_ENUMS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())