"""Intentional closed vocabularies for AES Logistics.

Each entry is a `intentional_closed_set` with provenance pointing at the live
source (record key or code constant). The freshness gate (extract_status_
vocabularies.py) hashes the source files and asserts the value sets actually
appear there, so a deleted/renamed location or a new status surfaces as a stale
snapshot instead of silent drift.

Never hand-duplicate these sh:in lists into curated SHACL — the generator owns
aesl_domain.shacl.enums.ttl.
"""
from __future__ import annotations

# target_class -> list of vocab dicts {id, property, values, required, provenance, note}
VOCABULARIES: dict[str, list[dict]] = {
    "Delivery": [
        {
            "id": "deliveryStatus",
            "property": "status",
            "values": ["scheduled", "ticket_uploaded", "packed", "en_route", "completed"],
            "required": True,
            "provenance": "intentional_closed_set@server/scheduling.py:135",
            "note": "status comment documents the full transition chain.",
        },
        {
            "id": "ticketSource",
            "property": "ticketSource",
            "values": ["uploaded", "generated"],
            "required": False,
            "provenance": "intentional_closed_set@server/scheduling.py:137,288,307",
            "note": "uploaded by save_ticket_file; generated by save_generated_ticket / revise_ticket.",
        },
    ],
    "InventoryEntry": [
        {
            "id": "removedReason",
            "property": "removedReason",
            "values": ["packed_for_outgoing_delivery", "manual"],
            "required": False,
            "provenance": "intentional_closed_set@specs/001-server/data-model.md:41",
            "note": "data-model.md documents the two reasons.",
        },
    ],
    "LocationSlit": [
        {
            "id": "storageLocation",
            "property": "location",
            "values": [
                "Warehouse", "Back Tent", "Front Tent", "Trailer 6", "Trailer 4",
                "Redbox", "Front Red", "CS 1036", "CS 1071", "CS 1058", "CS 1015",
                "Office", "Truck",
            ],
            "required": True,
            "provenance": "intentional_closed_set@server/inventory.py:23",
            "note": "server/inventory.py LOCATIONS — 13 fixed; a location must come from here.",
        },
    ],
    "SupplyItem": [
        {
            "id": "supplyStatus",
            "property": "supplyStatus",
            "values": ["in_stock", "below_threshold", "reorder"],
            "required": False,
            "provenance": "intentional_closed_set@specs/009-supply-jit/spec.md",
            "note": "Derived: on_hand > min_threshold = in_stock; on_hand < min_threshold = below_threshold; flagged = reorder. Closed set for MVP.",
        },
    ],
    "Geofence": [
        {
            "id": "geofenceTrigger",
            "property": "geofenceTrigger",
            "values": ["en_route_entry", "arrival"],
            "required": False,
            "provenance": "intentional_closed_set@specs/010-geofencing/spec.md",
            "note": "Spatial events emitted by the driver device; en_route_entry fires on first crossing into radius, arrival when inside after en_route.",
        },
    ],
}


def iter_vocabularies():
    for target_class, entries in VOCABULARIES.items():
        for e in entries:
            yield target_class, e